version: '3.8'

services:
  redis_server:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - observability_net

  observability_copilot:
    image: observability-copilot:v1
    container_name: observability-copilot
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - redis_server
    networks:
      - observability_net

networks:
  observability_net:
    driver: bridge
